### ISSUE TITLE
BLOM diagnostics: y-axis range seems unreliable for section transports when comparing experiments

### ISSUE THREAD

**Issue by matsbn** [NorESMhub/NorESM-Diagnostics#3]
Drake passage transport for experiment NOIIAJRAOC20TR_TL319_tn14_ppm_20240816 is shown here:
https://ns2345k.web.sigma2.no/datalake/diagnostics/noresm/matsbn/NOIIAJRAOC20TR_TL319_tn14_ppm_20240816/BLOM_DIAG/yrs1755to1774-obs/set1/set1_ann_voltr5_1model.png

Comparing NOIIAJRA_TL319_tn14_2.5a7_20241120 and NOIIAJRAOC20TR_TL319_tn14_ppm_20240816 is shown here:
https://ns2345k.web.sigma2.no/datalake/diagnostics/noresm/matsbn/NOIIAJRA_TL319_tn14_2.5a7_20241120/BLOM_DIAG/yrs42to61-NOIIAJRAOC20TR_TL319_tn14_ppm_20240816/set1/set1_ann_voltr5_2models.png

The transport time series of the first figure should be the same as the red transport time series of the second figure, but looking at the y-axis they differ.

**Comment by YanchunHe** [comment]
Thanks for reporting.

Seems the hidden 'second' y-axis does not use the same as the left y-axis. 

I will check that.

**Comment by YanchunHe** [comment]
| model-obs| model-model|
|--| --|
|![mod-obs](https://ns9560k.web.sigma2.no/datalake/diagnostics/noresm/yanchun/NOIIAJRAOC20TR_TL319_tn14_ppm_20240816/BLOM_DIAG/yrs1755to1774-obs/set1/set1_ann_voltr5_1model.png) | ![model-model](https://ns9560k.web.sigma2.no/datalake/diagnostics/noresm/yanchun/NOIIAJRAOC20TR_TL319_tn14_ppm_20240816/BLOM_DIAG/yrs1755to1774-NOIIAJRAOC20TR_TL319_tn14_pqm_20240816/set1/set1_ann_voltr5_2models.png) |

Now they should looks OK?

Please try with your case, and let me know so that I can merge the changes, and close the issue.

**Comment by matsbn** [comment]
Thanks for looking into this! Is the code updated on Betzy? That's where I have the experiments  readily available.

**Comment by YanchunHe** [comment]
> Thanks for looking into this! Is the code updated on Betzy? That's where I have the experiments readily available.

Yes, I update the Betzy installation now. Please try it on Betzy.

**Comment by matsbn** [comment]
I tried with the update and it looks good now, thanks!
